---
# tasks file for mytom7
- name: install tomcat7 on redhat
  yum: 
   name: tomcat
   state: present
- name: copy the tomcat config file into all nodes
  template:
   src: template/tomconfig.j2
   dest: /usr/share/tomcat/conf/tomcat.conf
  notify: tomstart
- name: install admin packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    -tomcat-webapps
    -tomcat-admin-webapps
- name: copy the tomcat user.xml file into all nodes
  template:
   src: template/tomuser.j2
   dest: /usr/share/tomcat/conf/tomcat.user.xml
  notify: tomrestart