---
- hosts: webserver
  become: yes
  tasks: 
  - name: install java on ubuntu
    apt:
     name: "{{ javaforubuntu }}"
     state: present
    when: ansible_os_family =="Debian"

  - name: install java on Redhat
    yum:
      name: "{{ javaforRedhat }}"
      state: present
    when: ansible_os_family =="Redhat"
   
