---
- hosts: all
  become: yes
  tasks:
  - name: remove webserver on ubuntu
    apt:
     name: apache2
     state: absent
  - name: install webserver on ubuntu
    apt:
     name: apache2
     state: present
     

     